# Generated by Django 4.2.11 on 2024-03-08 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_investmentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentForm',
            new_name='Investment',
        ),
    ]
