# Generated by Django 4.2.11 on 2024-03-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_investmentform_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='title',
            field=models.CharField(default='Investimento title', max_length=200),
        ),
    ]
