# Generated by Django 4.2.11 on 2024-03-10 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_expense_monthly_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='starting_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='number_of_years',
            field=models.IntegerField(default=0),
        ),
    ]
