# Generated by Django 4.2.11 on 2024-07-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_investment_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('pre', 'Pré-fixado'), ('pos', 'Pós-fixado')], default='pre', max_length=3),
        ),
        migrations.AddField(
            model_name='investment',
            name='rate_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('selic', 'SELIC')], max_length=5, null=True),
        ),
    ]
