# Generated by Django 4.2.11 on 2024-08-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_investment_investment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('pre', 'Pré-fixado'), ('pos', 'Pós-fixado')], default='pre', max_length=3),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('selic', 'SELIC')], max_length=5, null=True),
        ),
    ]
