# Generated by Django 4.2.11 on 2024-08-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_investment_investment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
    ]
