# Generated by Django 4.2.11 on 2024-09-17 18:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_investment_rate_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='rate_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rate_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.CharField(blank=True, default='inv', max_length=100),
        ),
    ]
